### ISSUE TITLE
BED file required instead of fasta

### ISSUE THREAD

**Issue by ghost** [SamaZYX/odintifier#1]
In the wiki, it is explained that the second reference you should give to the script is in fasta format. 

./phase_gatk.sh -r ref.fasta -b realigned.sort.bam -v vcf_file.vcf -c ref_2.fasta -o phase_gatk

However, in the script phased_consensus.R, it seems that R is expecting a second reference in a BED format, and not in fasta. Thus, when working with a fasta file as a second reference, the following error appears:

Error in read.table(args[4]) : no lines available in input

So I was wondering if the BED file was mandatory or if it was possible to run the script with a fasta file? 

Thanks a lot in advance,

Sarah

**Comment by SamaZYX** [comment]
Hi Sarah,

Are you running it with your own data? Or are you running the script with the test dataset in the example folder? 

If you are running it with your own data, the most likely explanation for this error is that you might not have "heterozygous" sites that can be linked in the phase step (cymt_numt_gatk.py). You might have this issue with these sites because they are not close enough or because you might not have "heterozygous" sites. The phase step is shown in Fig 1 of the [article](http://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-015-0682-1). 

You can check if you have phased sites in several ways:
- You can visualize your bam file using Tablet, IGV, samtools or Geneious to see if you have "heterozygous" sites very close to each other.
- Or you can check the phased vcf file for this sites.
- Also you can use the option -t or --tmp in ./phase_gatk.sh to leave the temporal files. You will then see a bed file. You can check in it if you have phased regions or not. 

If you don't have these "heterozygous" sites, it might be for several reasons, for example:
- Your species of interest might not have odins (numts/nupts/etc). 
- The odins of your species are very distant to organellar sequence, so that your mapping program can't align them to the organellar sequence.
- Or the odins of your species are very close to organellar sequence, in this case you will see few "heterozygous" sites in the bam file that are not very close from each other (physically) and therefor they can't be phased (if you have only single end reads).

Let me know your thoughts.

If you are running the script with the example, let me know so I can fix the problem.

Cheers,
Sama

**Comment by ghost** [comment]
Hi Sama,

Thanks for your answer. I'm actually running the script on the test dataset using the command you suggest in the wiki, so it should be something else; do you have any clue?

**Comment by SamaZYX** [comment]
Hi Sarah,

I just checked the scripts and datasets and they look good. 

In order to track down the problem, could you help me run some commands?

In the [wiki](https://github.com/SamaZYX/odintifier/wiki) there is an [example](https://github.com/SamaZYX/odintifier/wiki/Examples) page where you can find a small guide to run the example dataset.

Could you run the following command? And tell me if you have the same problem. :

`./phase_gatk.sh -r test_ref.fasta -b test.realigned.sort.bam -v vcf_file.vcf -c test_ref_2.fasta -o test_phase_gatk --tmp`

This command is a bit different from the one you posted above as the names of the references are different and I added the --tmp parameter.

Cheers,
Sama

**Comment by ghost** [comment]
Hi Sama,

I ran the command you mentionned with the test files and I still get the
same error. The following messages appear when running the command:

example$ ../phase_gatk.sh -r test_ref.fasta -b test.realigned.sort.bam -v
vcf_file.vcf -c test_ref_2.fasta -o test_phase_gatk --tmp

## INFO  14:37:06,363 HelpFormatter -

INFO  14:37:06,366 HelpFormatter - The Genome Analysis Toolkit (GATK)
v3.5-0-g36282e4, Compiled 2015/11/25 04:03:56
INFO  14:37:06,366 HelpFormatter - Copyright (c) 2010 The Broad Institute
INFO  14:37:06,367 HelpFormatter - For support and documentation go to
http://www.broadinstitute.org/gatk
INFO  14:37:06,371 HelpFormatter - Program Args: -T ReadBackedPhasing -R
test_ref.fasta -I test.realigned.sort.bam --variant vcf_file.vcf -o
vcf_file.phase.vcf --phaseQualityThresh 10.0
INFO  14:37:06,374 HelpFormatter - Executing as sschmid@Trollius on Linux
4.4.0-22-generic amd64; Java HotSpot(TM) 64-Bit Server VM 1.8.0_91-b14.
INFO  14:37:06,375 HelpFormatter - Date/Time: 2016/06/10 14:37:06

## INFO  14:37:06,375 HelpFormatter -

## INFO  14:37:06,375 HelpFormatter -

INFO  14:37:07,023 GenomeAnalysisEngine - Strictness is SILENT
INFO  14:37:07,155 GenomeAnalysisEngine - Downsampling Settings: Method:
BY_SAMPLE, Target Coverage: 1000
INFO  14:37:07,164 SAMDataSource$SAMReaders - Initializing SAMRecords in
serial
INFO  14:37:07,188 SAMDataSource$SAMReaders - Done initializing BAM
readers: total time 0.02
INFO  14:37:07,357 GenomeAnalysisEngine - Preparing for traversal over 1
BAM files
INFO  14:37:07,381 GenomeAnalysisEngine - Done preparing for traversal
INFO  14:37:07,382 ProgressMeter - [INITIALIZATION COMPLETE; STARTING
PROCESSING]
INFO  14:37:07,383 ProgressMeter -                 | processed |    time |
   per 1M |           |   total | remaining
INFO  14:37:07,383 ProgressMeter -        Location |     sites | elapsed |
    sites | completed | runtime |   runtime
INFO  14:37:37,389 ProgressMeter - test_mitochondria:16979     16384.0
 30.0 s      30.5 m       99.6%    30.0 s       0.0 s
INFO  14:38:07,401 ProgressMeter - test_mitochondria:16979     16384.0
 60.0 s      61.1 m       99.6%    60.0 s       0.0 s
INFO  14:38:37,412 ProgressMeter - test_mitochondria:16979     16384.0
 90.0 s      91.6 m       99.6%    90.0 s       0.0 s
INFO  14:39:07,413 ProgressMeter - test_mitochondria:16979     16384.0
120.0 s       2.0 h       99.6%   120.0 s       0.0 s
INFO  14:39:37,415 ProgressMeter - test_mitochondria:16979     16384.0
2.5 m       2.5 h       99.6%     2.5 m       0.0 s
INFO  14:40:07,417 ProgressMeter - test_mitochondria:16979     16384.0
3.0 m       3.1 h       99.6%     3.0 m       0.0 s
INFO  14:40:37,418 ProgressMeter - test_mitochondria:16979     16384.0
3.5 m       3.6 h       99.6%     3.5 m       0.0 s
INFO  14:41:07,420 ProgressMeter - test_mitochondria:16979     16384.0
4.0 m       4.1 h       99.6%     4.0 m       1.0 s
INFO  14:41:37,421 ProgressMeter - test_mitochondria:16979     16384.0
4.5 m       4.6 h       99.6%     4.5 m       1.0 s
INFO  14:42:07,422 ProgressMeter - test_mitochondria:16979     16384.0
5.0 m       5.1 h       99.6%     5.0 m       1.0 s
INFO  14:42:37,424 ProgressMeter - test_mitochondria:16979     16384.0
5.5 m       5.6 h       99.6%     5.5 m       1.0 s
Coverage over ALL samples:
Number of reads observed: 47622
Number of variant sites observed: 313
Average coverage: 152.14696485623003

--- Phasing summary [minimal haplotype quality (PQ): 10.0, maxPhaseSites:
10, cacheWindow: 20000] ---
Sample: 1test Sites tested: 3332 Sites phased: 287 Phase-inconsistent
sites: 6 [phased: 6, unphased:0]

INFO  14:42:55,813 ProgressMeter -            done     16860.0     5.8 m
    5.7 h       99.6%     5.8 m       1.0 s
INFO  14:42:55,814 ProgressMeter - Total runtime 348.43 secs, 5.81 min,
0.10 hours
INFO  14:42:55,817 MicroScheduler - 0 reads were filtered out during the
traversal out of approximately 25281 total reads (0.00%)
INFO  14:42:55,818 MicroScheduler -   -> 0 reads (0.00% of total) failing
BadCigarFilter
INFO  14:42:55,818 MicroScheduler -   -> 0 reads (0.00% of total) failing
DuplicateReadFilter
INFO  14:42:55,818 MicroScheduler -   -> 0 reads (0.00% of total) failing
FailsVendorQualityCheckFilter
INFO  14:42:55,818 MicroScheduler -   -> 0 reads (0.00% of total) failing
MalformedReadFilter
INFO  14:42:55,819 MicroScheduler -   -> 0 reads (0.00% of total) failing
MappingQualityZeroFilter
INFO  14:42:55,819 MicroScheduler -   -> 0 reads (0.00% of total) failing
NotPrimaryAlignmentFilter
INFO  14:42:55,820 MicroScheduler -   -> 0 reads (0.00% of total) failing
UnmappedReadFilter
INFO  14:42:57,051 GATKRunReport - Uploaded run statistics report to AWS S3
Loading required package: methods
Loading required package: BiocGenerics
Loading required package: parallel

Attaching package: ‘BiocGenerics’

The following objects are masked from ‘package:parallel’:

```
clusterApply, clusterApplyLB, clusterCall, clusterEvalQ,
clusterExport, clusterMap, parApply, parCapply, parLapply,
parLapplyLB, parRapply, parSapply, parSapplyLB
```

The following objects are masked from ‘package:stats’:

```
IQR, mad, xtabs
```

The following objects are masked from ‘package:base’:

```
anyDuplicated, append, as.data.frame, as.vector, cbind, colnames,
do.call, duplicated, eval, evalq, Filter, Find, get, grep, grepl,
intersect, is.unsorted, lapply, lengths, Map, mapply, match, mget,
order, paste, pmax, pmax.int, pmin, pmin.int, Position, rank,
rbind, Reduce, rownames, sapply, setdiff, sort, table, tapply,
union, unique, unlist, unsplit
```

Loading required package: S4Vectors
Loading required package: stats4
Loading required package: IRanges
Loading required package: XVector
Error in read.table(args[4]) : no lines available in input
Execution halted

Thanks again for the help

Sarah

Activé 10 juin 2016 à 14:05:21, SamaZYX (notifications@github.com) a écrit:

Hi Sarah,

I just checked the scripts and datasets and they look good.

In order to track down the problem, could you help me run some commands?

In the wiki https://github.com/SamaZYX/odintifier/wiki there is an example
https://github.com/SamaZYX/odintifier/wiki/Examples page where you can
find a small guide to run the example dataset.

Could you run the following command? And tell me if you have the same
problem. :

./phase_gatk.sh -r test_ref.fasta -b test.realigned.sort.bam -v
vcf_file.vcf -c test_ref_2.fasta -o test_phase_gatk --tmp

This command is a bit different from the one you posted above as the names
of the references are different and I added the --tmp parameter.

Cheers,
Sama

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/SamaZYX/odintifier/issues/1#issuecomment-225164751,
or mute
the thread
https://github.com/notifications/unsubscribe/AS666eIRLbqCzBQ8GaPntjmKOllf599-ks5qKVL1gaJpZM4IyDN_
.

**Comment by SamaZYX** [comment]
Hi Sarah,

I think I might have a hint on what is happening. I noticed that you are using GATK v3.5-0-g36282e4 and I am almost sure that it is conflicting with the scripts. I am currently using GATK v2.8 and it works fine.

When I finished the scripts time ago, GATK had just released the "new" version (v3.0) in that time. And while we were finishing the article we realized that the newer versions of GATK ( >= v3.0) had changed the format of their output files. That is why in [this](https://github.com/SamaZYX/odintifier/wiki/Requirements-to-run-scripts) part of the wiki it says that the scripts needs a version of GATK less than 3.0 in order to run.
So just try using an older version of GATK, 

Cheers,
Sama

**Comment by ghost** [comment]
Hi Sama,

Yes, that was it! I’m sorry not having noticing it before…

Just one more thing for people having trouble with GATK: GATK v2.8 runs
only with Java v1.7, not with Java v1.8.

Thanks a lot for your help

Sarah

Activé 10 juin 2016 à 15:51:49, SamaZYX (notifications@github.com) a écrit:

Hi Sarah,

I think I might have a hint on what is happening. I noticed that you are
using GATK v3.5-0-g36282e4 and I am almost sure that it is conflicting with
the scripts. I am currently using GATK v2.8 and it works fine.

When I finished the scripts time ago, GATK had just released the "new"
version (v3.0) in that time. And while we were finishing the article we
realized that the newer versions of GATK ( >= v3.0) had changed the format
of their output files. That is why in this
https://github.com/SamaZYX/odintifier/wiki/Requirements-to-run-scripts
part of the wiki it says that the scripts needs a version of GATK less than
3.0 in order to run.
So just try using an older version of GATK,

Cheers,
Sama

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/SamaZYX/odintifier/issues/1#issuecomment-225187376,
or mute
the thread
https://github.com/notifications/unsubscribe/AS666Tz_XR19EhWj7JWMWww3Dx7MPFasks5qKWvzgaJpZM4IyDN_
.

**Comment by SamaZYX** [comment]
Great that it worked!
